# Google App Engine configuration for AirSight
# This file defines the App Engine deployment configuration

runtime: java17
service: default
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource limits
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

# Environment variables
env_variables:
  # Application configuration
  ENVIRONMENT: production
  APP_PORT: "8080"
  LOG_LEVEL: INFO
  SHOW_SQL: "false"
  TZ: UTC
  
  # Database configuration (use Cloud SQL Proxy)
  DATABASE_URL: "jdbc:mysql://127.0.0.1:3306/airqualitydb?cloudSqlInstance=PROJECT_ID:REGION:INSTANCE_NAME&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false"
  
  # External API configuration
  OPENAQ_API_URL: "https://api.openaq.org/v2/latest"
  OPENAQ_TIMEOUT: "10000"
  
  # JVM configuration optimized for App Engine
  JAVA_OPTS: "-Xmx1536m -Xms768m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
  
  # Google Cloud specific
  GOOGLE_CLOUD_LOGGING_ENABLED: "true"
  GOOGLE_CLOUD_MONITORING_ENABLED: "true"

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 3
  healthy_threshold: 2
  restart_threshold: 300

# Liveness check
liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 1

# Readiness check
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 1
  app_start_timeout_sec: 300

# Network configuration
network:
  session_affinity: false
  
# Handlers for static content
handlers:
  # Serve frontend static files
  - url: /frontend
    static_dir: frontend
    secure: always

  # Serve API endpoints
  - url: /api/.*
    script: auto
    secure: always

  # Serve root and all other paths
  - url: /.*
    script: auto
    secure: always

# Beta settings for Cloud SQL
beta_settings:
  cloud_sql_instances: PROJECT_ID:REGION:INSTANCE_NAME