version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: airsight-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: airqualitydb
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${DB_USER:-airsight}
      MYSQL_PASSWORD: ${DB_PASSWORD:-airsightpass}
      TZ: ${TZ:-UTC}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_config:/etc/mysql/conf.d
    networks:
      - airsight-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-rootpassword}"]
      timeout: 10s
      retries: 5
      interval: 30s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    security_opt:
      - no-new-privileges:true

  # Redis for caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: airsight-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis.conf:ro
    networks:
      - airsight-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server /etc/redis.conf --appendonly yes
    security_opt:
      - no-new-privileges:true

  # AirSight Application
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: airsight-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/airqualitydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-airsight}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-airsightpass}
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL:-false}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      
      # Redis Configuration (optional)
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis
      
      # OpenAQ API Configuration
      OPENAQ_API_KEY: ${OPENAQ_API_KEY:-}
      OPENAQ_API_URL: https://api.openaq.org/v2/latest
      OPENAQ_API_TIMEOUT: 10000
      
      # Twilio Configuration (optional)
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER:-}
      
      # Application Configuration
      SERVER_PORT: 8080
      LOGGING_LEVEL_COM_AIR_AIRQUALITY: ${LOG_LEVEL:-INFO}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: WARN
      
      # CORS Configuration
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:5500,http://localhost:${NGINX_PORT:-80}
      
      # Production optimizations
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE: 25
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS: true
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES: true
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_VERSIONED_DATA: true
      
      # Security Configuration
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      
      # Timezone
      TZ: ${TZ:-UTC}
      
      # Java Options
      JAVA_OPTS: ${JAVA_OPTS:--Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0}
      
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - airsight-network
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true

  # Nginx Reverse Proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: airsight-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Add SSL certificates here
    depends_on:
      - app
    networks:
      - airsight-network
    profiles:
      - production  # Only start nginx in production profile

volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  airsight-network:
    driver: bridge
